package javausac;

import abstracto.Instruccion;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.StringReader;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.LinkedList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import Analisis.*;
import excepciones.Errores;
import instrucciones.AsignacionVar;
import instrucciones.Declaracion;
import instrucciones.Funcion;
import instrucciones.Metodo;
import instrucciones.Start;
import java.io.BufferedWriter;
import java.io.FileWriter;
import simbolo.*;
/**
 *
 * @author Fernando
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    public Interfaz() {
        initComponents();
        
        this.setLocationRelativeTo(null); // carga la ventana al centro de la pantalla
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    //lo siguiente que esta dentro del cuadro azul es generado automaticamente al cambiar el nombre de las variables de los botones
    // y lo siguiente de cuadro azul no es modificable.
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_archivo = new javax.swing.JButton();
        btn_ejecutar = new javax.swing.JButton();
        btn_reportes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_archivo.setText("Archivo");
        btn_archivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_archivoActionPerformed(evt);
            }
        });

        btn_ejecutar.setText("Ejecutar");
        btn_ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ejecutarActionPerformed(evt);
            }
        });

        btn_reportes.setText("Reportes");
        btn_reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportesActionPerformed(evt);
            }
        });

        jLabel1.setText("ENTRADA");

        jLabel2.setText("CONSOLA");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_archivo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_ejecutar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_reportes))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_archivo)
                    .addComponent(btn_ejecutar)
                    .addComponent(btn_reportes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

   
    private void btn_archivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_archivoActionPerformed
        // TODO add your handling code here:
        JFileChooser selectFile = new JFileChooser();
        
        int result = selectFile.showOpenDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION) {
            this.path = selectFile.getSelectedFile().getAbsolutePath();
            
            try {
                contenido = new String(Files.readAllBytes(Paths.get(this.path)));
                jTextArea2.setText(contenido);
                
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Error al leer el archivo: " + e.getMessage());
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "No selecciono ningun archivo.");

        }
        
    }//GEN-LAST:event_btn_archivoActionPerformed

    private void btn_ejecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ejecutarActionPerformed
        // TODO add your handling code here:
        LinkedList<Errores> lista =  new LinkedList<>();
        LinkedList<Errores> errores3 =  new LinkedList<>();
        String errores2="";
        String errores_sintacticos = "";
        String errores_semanticos = "";
        String htmlSintacticos = "";
        String htmlSemanticos = "";
        
        errores_sintacticos += "<table border='1'>\n";
        errores_sintacticos +="<tr><th>Tipo</th><th>Descripción</th><th>Línea</th><th>Columna</th></tr>\n";
        
        errores_semanticos += "<table border='1'>\n";
        errores_semanticos +="<tr><th>Tipo</th><th>Descripción</th><th>Línea</th><th>Columna</th></tr>\n";
        
        try {
                String texto = jTextArea2.getText();
                
                scanner s = new scanner(new BufferedReader(new StringReader(texto)));
                
                parser p = new parser(s);
                var resultado = p.parse();
                
                lista.addAll(s.listaErrores);
                lista.addAll(p.listaErrores);
                
                
                
                var ast = new Arbol((LinkedList<Instruccion>) resultado.value);
                
                
                
                if (!lista.isEmpty()) {
                    for (Errores e : lista) {
                        errores_sintacticos += "<tr>";
                        errores_sintacticos += "<td>"+e.getTipo()+"</td>"+
                                "<td>"+e.getDesc()+"</td>"+
                                "<td>"+e.getLinea() + "</td>"+
                                "<td>"+e.getColumna()+"</td>";
                        errores2 += "Tipo: "+e.getTipo()+ " Descripcion: "+e.getDesc()+ " Linea: "+e.getLinea() + " columna: "+e.getColumna()+"\n" ;
                    }
                    errores_sintacticos += "</table>\n";
                    
                    htmlSintacticos += "<!DOCTYPE html>\n"
                             + "<html>\n"
                             + "<head>\n"
                             + "<meta charset='UTF-8'>\n"
                             + "<title>Errores</title>\n"
                             + "</head>\n"
                             + "<body>\n"
                             + errores_sintacticos
                             + "</body>\n"
                             + "</html>";
                    
                    try (BufferedWriter writer = new BufferedWriter(new FileWriter("erroresSINTACTICOS.html"))) {
                        writer.write(htmlSintacticos);
                        System.out.println("Archivo HTML creado: errores.html");
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                    jTextArea1.setText(errores2);
                    return;
                }
                
                // ===== GENERAR AST =====
                int root = ast.getContador();
                ast.addAST("n" + root + "[label=\"INICIO\"];\n");

                for (Instruccion inst : ast.getInstructions()) {
                    if (inst == null) continue;
                    int h = inst.generarAST(ast);
                    ast.addAST("n" + root + " -> n" + h + ";\n");
                }
                
                try (BufferedWriter writer = new BufferedWriter(new FileWriter("ast.dot"))) {
                    writer.write(ast.getAST());
                    System.out.println("AST generado: ast.dot");
                } catch (IOException e) {
                    e.printStackTrace();
                }
                
                try {
                    ProcessBuilder pb = new ProcessBuilder(
                        "C:\\Program Files\\Graphviz\\bin\\dot.exe",
                        "-Tpng",
                        "ast.dot",
                        "-o",
                        "ast.png"
                    );
                    pb.start();
                } catch (IOException e) {
                    e.printStackTrace();
                }
                
                var tabla = new tablaSimbolos("GLOBAL", null);
                //tabla.setNombre("GLOBAL");
                ast.setConsoles("");
                
                Start st = null;
                
                for (var a : ast.getInstructions()) {

                    if (a instanceof Metodo || a instanceof Funcion) {
                        ast.addFunciones(a);
                    }

                    if (a instanceof Start) {
                        st = (Start) a;
                    }
                }
                
                for (var a : ast.getInstructions()) {

                    
                    if (a instanceof Metodo || a instanceof Funcion) {
                        continue;
                    }

                    
                    if (a instanceof Start) {
                        continue;
                    }

                    Object res = a.interpretar(ast, tabla);

                    if (res instanceof Errores) {
                        errores3.add((Errores) res);
                    }
                }
                
                if (st != null) {
                    Object res = st.interpretar(ast, tabla);
                    if (res instanceof Errores) {
                        errores3.add((Errores) res);
                    }
                }

                /*for (var a: ast.getInstructions()){
                    
                    
                    if (a instanceof Metodo){

                        ast.addFunciones(a);
                        continue;
                    }
                    
                    if (a instanceof Funcion){
                        
                        ast.addFunciones(a);
                        continue;
                    }
                    
                    Object res = a.interpretar(ast, tabla);
                    
                    if(res instanceof Errores){
                        errores3.add((Errores)res);
                    }

                    if (a instanceof Declaracion || a instanceof AsignacionVar){
                         //var res = a.interpretar(ast, tabla);
                         if (res instanceof Errores){
                             Errores errores = (Errores) res;
                             lista.add(errores);
                        }
                    }

                    if(a instanceof Start){

                        Start start = (Start) a; 
                        st = start;
                        
                    }
                }*/
                
                //var resultadoStart = st.interpretar(ast, tabla);
                
                /* for (var a: ast.getInstructions()){
                    if (a == null){
                        continue;
                    }
                    if (a instanceof Metodo){
                        
                       ast.addFunciones(a);
                    }

                }
                 
                for(var a : ast.getInstructions()){
                    if (a == null){
                        continue;
                    }
                    if (a instanceof Declaracion || a instanceof AsignacionVar){
                        var res = a.interpretar(ast, tabla);
                        if (res instanceof Errores){
                            Errores errores = (Errores) res;
                            lista.add(errores);
                        }
                    }
                }
                Start st = null;
                for(var a : ast.getInstructions()){
                    if (a == null){
                        continue;
                    }
                    if(a instanceof Start){
                       
                       Start start = (Start) a; 
                       st = start;
                       break;
                    }

                }
                var resultadoStart = st.interpretar(ast, tabla);*/
                
                //LinkedList<String[]> todosSimbolos = tabla.getAllSimbolosConAmbiente();
                LinkedList<String[]> todosSimbolos = new LinkedList<>();
                
                /*for (Object obj : tabla.getTablaActual().values()) {
                    Simbolo sim = (Simbolo) obj;
                    todosSimbolos.add(new String[]{
                        "GLOBAL",
                        sim.getId(),
                        sim.getTipo().getTipo().toString(),
                        String.valueOf(sim.getValor())
                    });
                }
                
                for (tablaSimbolos t : ast.getTablas()) {
                    String nombreAmbiente = t.getNombre().isEmpty() ? "ANONIMO" : t.getNombre();
                    for (Object obj : t.getTablaActual().values()) {
                        Simbolo sim = (Simbolo) obj;
                        todosSimbolos.add(new String[]{
                            nombreAmbiente,
                            sim.getId(),
                            sim.getTipo().getTipo().toString(),
                            String.valueOf(sim.getValor())
                        });
                    }
                }*/
                
                for (Object obj : tabla.getTablaActual().values()) {
                    Simbolo sim = (Simbolo) obj;

                    String valor;
                    if (sim.getValorlista() != null) {
                        valor = sim.getValorlista().toString();
                    } else {
                        valor = String.valueOf(sim.getValor());
                    }

                    todosSimbolos.add(new String[]{
                        "GLOBAL",
                        sim.getId(),
                        sim.getTipo().getTipo().toString(),
                        valor
                    });
                }

                
                for (tablaSimbolos t : ast.getTablas()) {
                    String nombreAmbiente = t.getNombre().isEmpty() ? "ANONIMO" : t.getNombre();

                    for (Object obj : t.getTablaActual().values()) {
                        Simbolo sim = (Simbolo) obj;

                        String valor;
                        if (sim.getValorlista() != null) {
                            valor = sim.getValorlista().toString();
                        } else {
                            valor = String.valueOf(sim.getValor());
                        }

                        todosSimbolos.add(new String[]{
                            nombreAmbiente,
                            sim.getId(),
                            sim.getTipo().getTipo().toString(),
                            valor
                        });
                    }
                }

                
                String htmlSimbolos = "<table border='1'>\n";
                htmlSimbolos += "<tr><th>Ambiente</th><th>ID</th><th>Tipo</th><th>Valor</th></tr>\n";

                for (String[] fila : todosSimbolos) {
                    htmlSimbolos += "<tr>";
                    htmlSimbolos += "<td>" + fila[0] + "</td>";
                    htmlSimbolos += "<td>" + fila[1] + "</td>";
                    htmlSimbolos += "<td>" + fila[2] + "</td>";
                    htmlSimbolos += "<td>" + fila[3] + "</td>";
                    htmlSimbolos += "</tr>\n";
                }

                htmlSimbolos += "</table>\n";

                String htmlCompleto = "<!DOCTYPE html>\n<html>\n<head>\n<meta charset='UTF-8'>\n<title>Tabla de Símbolos</title>\n</head>\n<body>\n" 
                                    + htmlSimbolos 
                                    + "</body>\n</html>";

                try (BufferedWriter writer = new BufferedWriter(new FileWriter("tablaSimbolos.html"))) {
                    writer.write(htmlCompleto);
                    System.out.println("Archivo HTML creado: tablaSimbolos.html");
                } catch (IOException e) {
                    e.printStackTrace();
                }
                
                
                if(!errores3.isEmpty()){
                    for(Errores e: errores3){
                        errores2 += "Tipo: "+e.getTipo()+ " Descripcion: "+e.getDesc()+ " Linea: "+e.getLinea() + " columna: "+e.getColumna()+"\n";
                        errores_semanticos += "<tr>";
                        errores_semanticos += "<td>"+e.getTipo()+"</td>"+
                                "<td>"+e.getDesc()+"</td>"+
                                "<td>"+e.getLinea() + "</td>"+
                                "<td>"+e.getColumna()+"</td>";
                        
                   
                    
                    }
                    
                    errores_semanticos += "</table>\n";
                    
                    htmlSintacticos += "<!DOCTYPE html>\n"
                             + "<html>\n"
                             + "<head>\n"
                             + "<meta charset='UTF-8'>\n"
                             + "<title>Errores</title>\n"
                             + "</head>\n"
                             + "<body>\n"
                             + errores_semanticos
                             + "</body>\n"
                             + "</html>";
                    
                    try (BufferedWriter writer = new BufferedWriter(new FileWriter("erroresSEMANTICOS.html"))) {
                        writer.write(htmlSintacticos);
                        System.out.println("Archivo HTML creado: errores.html");
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                    
                    
                    jTextArea1.setText(errores2);
                    
                    
                    
                    return;
                }
                
                jTextArea1.setText(ast.getConsoles());
                
                
        } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Error al cargar el archivo: " + e.getMessage());
        } catch(Exception ex){
            
            
            //System.out.println("ESTOY AQUI2");
            jTextArea1.setText("ERROR\n"); 
        }
        
        

        
    }//GEN-LAST:event_btn_ejecutarActionPerformed

    private void btn_reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_reportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }
    
    String path;
    String contenido;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_archivo;
    private javax.swing.JButton btn_ejecutar;
    private javax.swing.JButton btn_reportes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
