
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 48;
  public static final int _new = 33;
  public static final int POR = 43;
  public static final int _CHAR = 14;
  public static final int CHAR = 34;
  public static final int IGUALACION = 56;
  public static final int FIND = 19;
  public static final int MENORQ = 58;
  public static final int _return = 31;
  public static final int ENTERO = 3;
  public static final int corcheteC = 52;
  public static final int DIFERENTE = 57;
  public static final int XOR = 53;
  public static final int corcheteA = 51;
  public static final int DOUBLE = 11;
  public static final int PORCENTAJE = 42;
  public static final int _do = 29;
  public static final int llaveder = 50;
  public static final int INT = 10;
  public static final int PUNTOCOMA = 35;
  public static final int _switch = 25;
  public static final int MENORIGUAL = 59;
  public static final int AND = 54;
  public static final int IGUAL = 47;
  public static final int OR = 55;
  public static final int PARCIERRA = 38;
  public static final int BOOL = 12;
  public static final int _else = 24;
  public static final int DIV = 44;
  public static final int _list = 32;
  public static final int UMENOS = 62;
  public static final int EXCLAMACION = 41;
  public static final int ID = 5;
  public static final int MAYORIGUAL = 61;
  public static final int EOF = 0;
  public static final int DECIMAL = 4;
  public static final int TRUE = 21;
  public static final int error = 1;
  public static final int _break = 6;
  public static final int COMA = 67;
  public static final int CADENA = 2;
  public static final int MENOS = 40;
  public static final int MENOR = 45;
  public static final int START = 68;
  public static final int TOSTRING = 18;
  public static final int VOID = 66;
  public static final int ERROR = 65;
  public static final int _continue = 7;
  public static final int MAYOR = 46;
  public static final int _if = 23;
  public static final int POTENCIA = 64;
  public static final int _default = 27;
  public static final int _while = 28;
  public static final int PUNTO = 36;
  public static final int MAYORQ = 60;
  public static final int _remove = 16;
  public static final int CASTEO = 63;
  public static final int _for = 30;
  public static final int llaveizq = 49;
  public static final int _case = 26;
  public static final int PARABRE = 37;
  public static final int STRING = 13;
  public static final int FALSE = 22;
  public static final int VAR = 9;
  public static final int PRINT = 8;
  public static final int LENGTH = 17;
  public static final int ROUND = 20;
  public static final int _append = 15;
  public static final int MAS = 39;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "ENTERO",
  "DECIMAL",
  "ID",
  "_break",
  "_continue",
  "PRINT",
  "VAR",
  "INT",
  "DOUBLE",
  "BOOL",
  "STRING",
  "_CHAR",
  "_append",
  "_remove",
  "LENGTH",
  "TOSTRING",
  "FIND",
  "ROUND",
  "TRUE",
  "FALSE",
  "_if",
  "_else",
  "_switch",
  "_case",
  "_default",
  "_while",
  "_do",
  "_for",
  "_return",
  "_list",
  "_new",
  "CHAR",
  "PUNTOCOMA",
  "PUNTO",
  "PARABRE",
  "PARCIERRA",
  "MAS",
  "MENOS",
  "EXCLAMACION",
  "PORCENTAJE",
  "POR",
  "DIV",
  "MENOR",
  "MAYOR",
  "IGUAL",
  "DOSPUNTOS",
  "llaveizq",
  "llaveder",
  "corcheteA",
  "corcheteC",
  "XOR",
  "AND",
  "OR",
  "IGUALACION",
  "DIFERENTE",
  "MENORQ",
  "MENORIGUAL",
  "MAYORQ",
  "MAYORIGUAL",
  "UMENOS",
  "CASTEO",
  "POTENCIA",
  "ERROR",
  "VOID",
  "COMA",
  "START"
  };
}

